# This is a basic workflow to help you get started with Actions

name: Build zip package for WP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - "v*.*.*"

jobs:
  package-as-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package
        uses: papeloto/action-zip@v1
        with:
          files: anemitoff-wp-proxied.php
          dest: anemitoff-wp-proxied.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: anemitoff-wp-proxied.zip